# Data Preparation Basics
## Part 5 - Grouping and data aggregation

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

### Grouping data by column index

The mtcars dataset appears to contain a variety of information about cars, including their fuel efficiency, engine characteristics, weight, and performance-related features. It's a common type of dataset used for analyzing and comparing different car models.

## Here's a description of each column in the dataset:
**ar_names**: This column likely contains the names or identifiers of different car models. Each row represents a specific car in the dataset.


**mpg**: This column typically represents the miles per gallon (mpg) or fuel efficiency of each car. It measures how many miles a car can travel per gallon of fuel. Higher values indicate better fuel efficiency.


**cyl**: This column likely represents the number of cylinders in the car's engine. It's a measure of engine size and power. Common values include 4, 6, or 8 cylinders.


**disp**: This column might represent engine displacement, which is the total volume of air/fuel mixture an engine can draw in during one complete engine cycle. It is typically measured in cubic inches (or liters). Engine displacement is related to the car's performance and power.


**hp**: This column is likely the horsepower (hp) rating of the car's engine. Horsepower is a measure of the engine's power output. Higher values generally indicate more powerful engines.


**drat**: This column could represent the "drivetrain" or "rear axle ratio." The rear axle ratio affects the car's acceleration and fuel efficiency. It represents the ratio of the number of revolutions of the driveshaft to one revolution of the rear wheel.


**wt**: This column likely represents the weight (in some units, such as pounds or kilograms) of the car. The car's weight can impact its handling, fuel efficiency, and performance.


**qsec**: This column might represent the time (in seconds) it takes for the car to accelerate from 0 to 60 miles per hour (or a similar measure). It's a performance metric, and lower values generally indicate faster acceleration.


**vs**: This column could represent the "engine type" or "engine configuration." Common values include 0 and 1, which might indicate a V-shaped engine (V6 or V8) and an inline engine (4 or 6 cylinders), respectively.


**am**: This column might represent whether the car has an automatic (0) or manual (1) transmission. It's an indicator of the car's transmission type.


**gear**: This column likely represents the number of forward gears in the car's transmission. It can affect the car's performance and driving experience.


**carb**: This column could represent the number of carburetors in the car's engine. Carburetors are components that mix air and fuel for combustion in older vehicles. The number of carburetors can affect engine performance and fuel delivery.

In [2]:
address = '/content/sample_data/mtcars.csv'

cars = pd.read_csv(address)

cars.columns = ['car_names', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']
cars.head(10)

,car_names,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4

In [ ]:
cars_groups = cars.groupby(cars['cyl'])
cars_groups.mean()

,mpg,disp,hp,drat,wt,qsec,vs,am,gear,carb
cyl,,,,,,,,,,
4,26.663636,105.136364,82.636364,4.070909,2.285727,19.137273,0.909091,0.727273,4.090909,1.545455
6,19.742857,183.314286,122.285714,3.585714,3.117143,17.977143,0.571429,0.428571,3.857143,3.428571
8,15.100000,353.100000,209.214286,3.229286,3.999214,16.772143,0.000000,0.142857,3.285714,3.500000

In [ ]:
cars.describe

<bound method NDFrame.describe of               car_names   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1

    gear  carb
0      4     4
1      4     4
2      4     1
3      3     1
4      3     2
5      3     1
6      3     4
7      4     2
8      4     2
9      4     4
10     4     4
11     3     3
12     3     3
13     3     3
14     3     4
15     3     4
16     3     4
17     4     1
18     4     2
19     4     1
20     3     1
21     3     2
22     3     2
23     3     4
24     3     2
25     4     1
26     5     2
27     5     2
28     5     4
29     5     6
30     5     8
31     4     2  >